### ISSUE TITLE
tb-updater do not populate home directory at first boot

### ISSUE THREAD

**Issue by marmarek** [Whonix/tb-updater#2]
On Qubes 4.0, tor browser isn't copied into user home directory on first VM startup.
It is caused by this code:
https://github.com/Whonix/tb-updater/blob/1766f0222e6502f5b43d9e4938a64ca8a24b500d/usr/lib/tb-updater/first-boot-home-population#L10-L14

The flag file is stored in /var/cache (which is shared between TemplateVM and TemplateBasedVMs), so if home directory is populated in the template itself (if for any reason check for being TemplateVM fails), then no further TemplateBasedVM will receive tor browser. Especially, this breaks DispVMs based on whonix-ws-dvm, because it tries to download tor browser at each start.

I'm not sure why check for TemplateVM fails, but regardless of investigating it, I propose moving flag file into user home (something that have the same persistence property as actual provisioned tor browser).

**Comment by adrelanos** [comment]
Already existing:

https://github.com/Whonix/qubes-whonix/blob/master/usr/lib/qubes-bind-dirs.d/40_qubes-whonix.conf#L11

> `binds+=( '/var/cache/tb-updater' )`

Why doesn't that work?

**Comment by marmarek** [comment]
For some reason it doesn't get mounted. bind-dirs log:
```
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/spool/cron onto /var/spool/cron
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/lib/tor onto /var/lib/tor
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/lib/whonix onto /var/lib/whonix
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/lib/whonixcheck onto /var/lib/whonixcheck
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/cache/whonix-setup-wizard onto /var/cache/whonix-setup-wizard
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/var/cache/anon-base-files onto /var/cache/anon-base-files
Mar 26 17:18:55 host mount-dirs.sh[318]: Bind mounting /rw/bind-dirs/etc/tor onto /etc/tor
```
Looks like `/var/cache/tb-updater` directory didn't existed at mount-dirs.sh call time (?!). 

Anyway, this looks wrong. If `/var/cache/tb-updater` is bind-mounted to /rw, then cached tor browser will be (1) copied to /rw and (2) no further updates (of tb-updater package) will be visible to that VM. Not sure if (2) is problematic (probably not, because it is meant to be used once anyway), but (1) means tor browser will be in /rw twice - once in /rw/bind-dirs, and once in /user/home (/rw/home/user).

**Comment by marmarek** [comment]
The above isn't fully accurate. tb-updater saves downloaded TB into `/var/cache/tb-binary`, not `/var/cache/tb-updater`, so it won't be copied twice into `/rw`.
But this explains why `/var/cache/tb-updater` isn't there - it is created only at the end of `first-boot-home-population`, which is after bind-dirs are processed. This is why the bind-dirs don't work here.

This is still inconsistent, because if `/var/cache/tb-updater` wasn't initially there, it wasn't the reason for skipping `first-boot-home-population`.

Unfortunately, in the process of debugging this, I've fixed my whonix-ws-dvm (or whonix-ws?) and can no longer reproduce the problem. I'll check again after reinstall.

**Comment by adrelanos** [comment]
Folder `/var/cache/tb-updater` should exist because there is already existing file `/var/cache/tb-updater/placeholder`. 

https://github.com/Whonix/tb-updater/blob/master/var/cache/tb-updater/placeholder

I'll be moving the done_file to the home folder. Dunno if that will fix the issue.

**Comment by adrelanos** [comment]
Previously I avoided writing to home folder since this can easily mess up file permissions.

https://github.com/Whonix/tb-updater/commit/8a923d959fb2c0a3e2a4af554cfb2decef0dfa91

**Comment by marmarek** [comment]
After rebuilding Whonix 13 template, it looks to be working (populating torbrowser in home directory). Probably I haven't whonix-ws template itself before, so it didn't populated home directory there.
But there is still no `/var/cache/tb-updater/placeholder`.

Oh, maybe you were talking about Whonix 14?

**Comment by adrelanos** [comment]
Whonix 14 only. I don't think it's worth to look into Whonix 14 anymore
since it's based on horribly outdated Debian jessie.

I could use some help with Whonix 14 bug fixing so it gets finally
released so we can forget about Whonix 13.

**Comment by adrelanos** [comment]
https://phabricator.whonix.org/T789
